#!/bin/bash
#PBS -N mr-mpi
#PBS -n -l nodes=1:ppn=20
#PBS -l walltime=00:20:00

source config.h
echo "program:"$EXE
echo "param:"$PARAM
echo "input dir:"$INDIR
echo "prefix":$PREFIX
echo "output dir:"$OUTDIR
echo "temp dir:"$TMPDIR
echo "tau outfile:"$TAUFILE
mpiexec -n $PPN -bind-to core ./$EXE $PARAM $INDIR $PREFIX.TAU $OUTDIR $TMPDIR
pprof | grep "  Heap Memory Used (KB)" | awk -v np=$PPN -v data=$DATASIZE '{print data","np","i++","$2}' >> $TAUFILE
rm profile.*
