#!/bin/bash
#SBATCH --job-name="mtmr-mpi"  
#SBATCH --output="mtmr-mpi.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --export=ALL  
#SBATCH --ntasks-per-core=1
#SBATCH -v -t 00:20:00

SUBDIR=n1

source common.h
#export OMP_NUM_THREADS=$NTHRS
export MV2_ENABLE_AFFINITY=1
export MV2_CPU_BINDING_LEVEL=core
export MV2_SHOW_CPU_BINDING=1
ibrun -v -bp=none ./$EXE $INDIR $PREFIX $OUTDIR
