#!/bin/bash
#SBATCH --job-name="mtmr-mpi"  
#SBATCH --output="mtmr-mpi.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --export=ALL  
#SBATCH --ntasks-per-core=1
#SBATCH -v -t 00:20:00

SUBDIR=4G
source common.h

#export MV2_USE_HUGEPAGES=1
export MV2_ENABLE_AFFINITY=1
export MV2_SHOW_CPU_BINDING=1
ibrun -bp=none -v ./$EXE $INDIR/$SUBDIR $PREFIX $OUTDIR $TMPDIR
