PPN=24
BENCHMARK=wordcount
SETTING=onenode
DATASET=uniform
#DATASIZE=
#EXE=wordcount
PARAM=

BASEDIR=/oasis/scratch/comet/taogao/temp_project
INDIR=$BASEDIR/$BENCHMARK/$DATASET/$SETTING/$DATASIZE
PREFIX=mtmrmpi-$BENCHMARK-$SETTING-$DATASET-$DATASIZE
OUTDIR=$BASEDIR/results/paper
TMPDIR=/scratch/$USER/$SLURM_JOB_ID

TAUFILE=mtmrmpi-$EXE-$BENCHMARK-$SETTING-$DATASET.txt
