#!/bin/bash
#SBATCH --job-name="mtmr-mpi"  
#SBATCH --output="mtmr-mpi.%j.%N.out"  
#SBATCH --partition=compute
#SBATCH --ntasks-per-node=24
#SBATCH --export=ALL  
#SBATCH -t 00:30:00

source config.h

echo "node:"$NODE
echo "ppn:"$PPN
echo "program:"$EXE
echo "param:"$PARAM
echo "input dir:"$INDIR
echo "prefix":$PREFIX
echo "output dir:"$OUTDIR
echo "test index:"$TESTINDEX

let NPROC=PPN*NODE

mpiexec -n $NPROC -bind-to core ./$EXE $PARAM $INDIR $PREFIX $OUTDIR $TMPDIR $TESTINDEX


