#!/bin/bash
#SBATCH --job-name="mtmr-mpi"  
#SBATCH --output="mtmr-mpi.%j.%N.out"  
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --export=ALL  
#SBATCH -t 02:00:00

source config.h

echo "program:"$EXE
echo "param:"$PARAM
echo "input dir:"$INDIR
echo "prefix":$PREFIX
echo "output dir:"$OUTDIR
echo "temp dir:"$TMPDIR

mpiexec -n $PPN -bind-to core ./$EXE $PARAM $INDIR $PREFIX $OUTDIR $TMPDIR
