#!/bin/bash
#SBATCH --job-name="mtmr-mpi"  
#SBATCH --output="mtmr-mpi.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --export=ALL  
#SBATCH --ntasks-per-core=1
#SBATCH -v -t 01:00:00

SUBDIR=$1
source common.h

mpiexec -n $PPN -bind-to core ./$EXE $INDIR/$SUBDIR $PREFIX$1 $OUTDIR $TMPDIR

#export MV2_USE_HUGEPAGES=1
#export MV2_ENABLE_AFFINITY=1
#export MV2_SHOW_CPU_BINDING=1
#ibrun -bp=none -v ./$EXE $INDIR/$SUBDIR $PREFIX $OUTDIR $TMPDIR
