#!/bin/bash
#SBATCH --job-name="generate-octree"  
#SBATCH --output="generate-octree.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --export=ALL  
#SBATCH --ntasks-per-core=1
#SBATCH -v -t 04:00:00

SIDX=$1
NFILE=$2
COUNT=$3
DIST=$4
STDIV=$5
OUTDIR=$6
TMPDIR=$7

PREFIX=rr

#python gen_key_point_rr.py $PREFIX $TMPDIR $NFILE $STDIV  1 0 0 0 $COUNT $DIST
#echo "generate points end."
./gen_syn_data.sh one_ligand.txt $SIDX $NFILE $TMPDIR $OUTDIR $PREFIX
echo "generate data end."
#rm $OUTDIR/$PREFIX.keys*
#rm $OUTDIR/$PREFIX.points*
#echo "remove data."
