#!/bin/bash
#SBATCH --job-name="mtmr-mpi"  
#SBATCH --output="mtmr-mpi.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --export=ALL  
#SBATCH --ntasks-per-core=1
#SBATCH -v -t 01:00:00

echo "thread number:"$THRS
echo "input dir:"$INPUT
echo "output dir:"$OUTPUT
echo "prefix:"$PREFIX
echo "file size:"$FSIZE
echo "start index":$SIDX
echo "file count":$NFILE

OMP_NUM_THREADS=$THRS ./split_text_files $INPUT $OUTPUT $PREFIX $FSIZE $SIDX $NFILE
