#!/bin/bash
#SBATCH --job-name="wordgenerator"  
#SBATCH --output="wordgenerator.%j.%N.out"
#SBATCH --partition=compute  
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --export=ALL  
#SBATCH --ntasks-per-core=1
#SBATCH -v -t 00:20:00

DATAHOME=/oasis/scratch/comet/taogao/temp_project/wordcount/uniform
SUBDIR=weekscale/test

python wordgenerator.py uniform 100000 1398101 24 words $DATAHOME/$SUBDIR
