#!/bin/bash
#SBATCH --job-name="wordgenerator"  
#SBATCH --output="wordgenerator.%j.%N.out"
#SBATCH --partition=compute  
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --export=ALL  
#SBATCH --ntasks-per-core=1
#SBATCH -v -t 00:20:00

DATAHOME=/oasis/scratch/comet/taogao/temp_project/
INPUTDIR=words/triangular
FULLNAME=1G.txt

FULLNAME=$DATAHOME/$INPUTDIR/$FULLNAME

#cd $PBS_O_WORKDIR
#module load python/2.7.2
python wordcountgen.py tmp.config.txt > $FULLNAME
ls -l $FULLNAME
