#!/bin/bash
#SBATCH --job-name="wordgenerator"  
#SBATCH --output="wordgenerator.%j.%N.out"
#SBATCH --partition=debug 
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --export=ALL  
#SBATCH --ntasks-per-core=1
#SBATCH -v -t 00:30:00

echo "distribute",$DIST
echo "unique",$UNIQUE
echo "fsize",$FSIZE
echo "offset",$OFFSET
echo "nfile",$NFILE
echo "prefix",$PREFIX
echo "outdir",$OUTDIR

python wordgenerator.py $DIST $UNIQUE $FSIZE $OFFSET $NFILE $PREFIX $OUTDIR
